name: anisi_controls
description: A couple of my own custom made controls you may find useful to your flutter project
version: 0.1.1
homepage: https://github.com/jacksiroke/anisi_controls

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^3.0.1
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jacksiroke.anisi_controls
        pluginClass: AnisiControlsPlugin
      ios:
        pluginClass: AnisiControlsPlugin
